Update script

diff --git a/script b/script
--- a/script
+++ b/script
@@ -95,6 +95,12 @@ wget http://wordpress.org/latest.zip --no-check-certificate				#downloading word
 service mysqld restart
 mysqladmin -u root password mysql							#setting mysql password for root
 mysql -u root -pmysql -e 'create database example.com_db'				#creating new database
+	if [ $? -eq 0 ]; then
+		echo 'New database created successfully...'
+	else
+		echo 'Failed to create new database...'
+		exit 1
+	fi
 
 #-------------------------------------------------------------------------------------------------------------------
 
